# Generated by Django 3.2.9 on 2021-11-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strcategory', models.CharField(max_length=30)),
                ('strcategorythumb', models.URLField(max_length=100)),
                ('strcategorydescribtion', models.TextField()),
            ],
        ),
    ]
