# Generated by Django 3.2.9 on 2021-11-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_meals'),
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmeal', models.IntegerField()),
                ('strMeal', models.CharField(max_length=100)),
                ('strDrinkAlternate', models.CharField(max_length=100, null=True)),
                ('strcategory', models.CharField(max_length=100)),
                ('strArea', models.CharField(max_length=100)),
                ('strInstruction', models.CharField(max_length=1000)),
                ('strmealthumb', models.FileField(upload_to='')),
                ('strTags', models.CharField(max_length=100)),
                ('strYoutube', models.URLField(max_length=100)),
                ('strIngridient1', models.CharField(max_length=100)),
                ('strIngridient2', models.CharField(max_length=100)),
                ('strIngridient3', models.CharField(max_length=100)),
                ('strIngridient4', models.CharField(max_length=100)),
                ('strIngridient5', models.CharField(max_length=100)),
                ('strIngridient6', models.CharField(max_length=100)),
                ('strIngridient7', models.CharField(max_length=100)),
                ('strIngridient8', models.CharField(max_length=100)),
                ('strIngridient9', models.CharField(max_length=100)),
                ('strIngridient10', models.CharField(max_length=100)),
                ('strIngridient11', models.CharField(max_length=100)),
                ('strIngridient12', models.CharField(max_length=100)),
                ('strIngridient13', models.CharField(max_length=100)),
                ('strIngridient14', models.CharField(max_length=100)),
                ('strIngridient15', models.CharField(max_length=100)),
                ('strIngridient16', models.CharField(max_length=100)),
                ('strIngridient17', models.CharField(max_length=100)),
                ('strIngridient18', models.CharField(max_length=100)),
                ('strIngridient19', models.CharField(max_length=100)),
                ('strIngridient20', models.CharField(max_length=100)),
                ('strMeasure1', models.CharField(max_length=100)),
                ('strMeasure2', models.CharField(max_length=100)),
                ('strMeasure3', models.CharField(max_length=100)),
                ('strMeasure4', models.CharField(max_length=100)),
                ('strMeasure5', models.CharField(max_length=100)),
                ('strMeasure6', models.CharField(max_length=100)),
                ('strMeasure7', models.CharField(max_length=100)),
                ('strMeasure8', models.CharField(max_length=100)),
                ('strMeasure9', models.CharField(max_length=100)),
                ('strMeasure10', models.CharField(max_length=100)),
                ('strMeasure11', models.CharField(max_length=100)),
                ('strMeasure12', models.CharField(max_length=100)),
                ('strMeasure13', models.CharField(max_length=100)),
                ('strMeasure14', models.CharField(max_length=100)),
                ('strMeasure15', models.CharField(max_length=100)),
                ('strMeasure16', models.CharField(max_length=100, null=True)),
                ('strMeasure17', models.CharField(max_length=100)),
                ('strMeasure18', models.CharField(max_length=100)),
                ('strMeasure19', models.CharField(max_length=100)),
                ('strMeasure20', models.CharField(max_length=100)),
                ('strsource', models.CharField(max_length=100, null=True)),
                ('strImageSource', models.CharField(max_length=100, null=True)),
                ('strCreativeCommonsConfirmed', models.CharField(max_length=100, null=True)),
                ('dateModified', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
