# Generated by Django 3.2.9 on 2021-11-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='dateModified',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='strCreativeCommonsConfirmed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='strDrinkAlternate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='strImageSource',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='strIngridient10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strIngridient11',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strIngridient12',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strIngridient13',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strIngridient14',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strIngridient15',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strIngridient16',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strIngridient17',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strIngridient18',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strIngridient19',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strIngridient20',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strIngridient9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strMeasure10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strMeasure11',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strMeasure12',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strMeasure13',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strMeasure14',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strMeasure15',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strMeasure16',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='strMeasure17',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strMeasure18',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strMeasure19',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strMeasure20',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strMeasure9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='strsource',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
