# Generated by Django 3.2.9 on 2021-11-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20211108_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='strcategorythumb',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='meals',
            name='strmealthumb',
            field=models.FileField(upload_to=''),
        ),
    ]
